BaseURL = "https://synflux.io"
baseURL = "https://synflux.io"
languageCode = "en-us"
title = "Synflux"
relativeURLs = false
publishDir = "docs"

[languages]
    [languages.en]
        languageName = "English"
        title = "Synflux"
        contentDir = "content/en"
        weight = "1"
    [languages.jp]
        languageName = "Japanese"
        title = "シンフラックス"
        contentDir = "content/jp"
        weight = "2"