backend:   
  name: github
  repo: kkshmz/synflux.io # GitHubのリポジトリ　「https://github.com/」の後ろの部分
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/img/" # Media files will be stored in the repo under static/images/uploads
 # The src attribute for uploaded media will begin with /images/uploads
public_folder: "/public"

collections:
  - label: "Projects" # 管理画面のサイドバーで使う
    name: "projects" # 管理画面のパスで使う　例：/admin/collections/blog
    folder: "content/projects" # Markdownを保存するディレクトリ。Hugoのsectionにあたる
    create: true # 新しいページを作ることを許可する
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Markdownのファイル名　例：YYYY-MM-DD-title.md
    fields: # ページ作成画面で使う。Front Matterの値を書く
      - {label: "タイトル", name: "Project Title", widget: "string"}
      - {label: "公開日", name: "Project Date", widget: "datetime"}
      - {label: "サムネイル画像", name: "Project thumbnail", widget: "image"}
      - {label: "カテゴリー", name: "Category", widget: "string"}
      - {label: "本文", name: "body", widget: "markdown"}
  - label: "Information" 
    name: "Information"
    folder: "content/information"
    create: false # 新しいページを作ることを許可する
    fields: # ページ作成画面で使う。Front Matterの値を書く
      - {label: "タイトル", name: "Project Title", widget: "string"}
      - {label: "公開日", name: "Project Date", widget: "datetime"}
      - {label: "サムネイル画像", name: "Project thumbnail", widget: "image"}
      - {label: "カテゴリー", name: "Category", widget: "string"}
      - {label: "本文", name: "body", widget: "markdown"}