---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/jp/information
  label: JP Information
  create: all
  match: "**/*"
  templates:
  - information
- type: directory
  path: content/jp/projects
  label: JP Projects
  create: all
  match: "**/*"
  templates:
  - project
- type: directory
  path: content/en/information
  label: EN Information
  create: all
  match: "**/*"
- type: directory
  path: content/en/projects
  label: EN Projects
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: static/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: true
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d docs
  preview_env:
  - HUGO_ENV=development
  - HUGO_VERSION=0.55.5
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.55.5
  preview_output_directory: public
  output_directory: docs
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: '0.53'
