---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/jp/projects
  label: JP Projects
  create: all
  match: "**/*"
  templates:
  - project
- type: directory
  path: content/en/projects
  label: EN Projects
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "**/*"
upload_dir: static/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=development
  - HUGO_VERSION=0.55.5
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: '0.53'
