---
label: Project
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
  description: Enter in project name
  config:
    required: true
- name: date
  label: Date
  type: datetime
  hidden: false
  default: ''
  description: Enter in the year of the project YY/MM
  config:
    date_format: YY/MM
- type: textarea
  name: description
  label: Description
  description: Description of the project
  config:
    wysiwyg: true
    schema:
      format: markdown
- type: image_gallery
  label: Project Images
  name: project_images
  description: 'Images from the project '
- type: text
  name: draft
  label: draft
  hidden: true
  default: 'false'
- type: text
  hidden: true
  label: layout
  name: layout
  default: single
- type: text
  name: type
  label: type
  hidden: true
  default: projects
- name: priority
  type: text
  config:
    required: false
  label: priority
  hidden: false
